import json
from pathlib import Path
import uuid

def generate_sql():
    # 讀取解析後的資料
    json_path = Path("./final_data_package.json")
    if not json_path.exists():
        print("❌ 找不到 final_data_package.json，請先執行 parse_final_v2.py")
        return

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    employees = data["employees"]
    task_matrices = data["task_matrix"]

    # 準備 SQL 內容
    sql = []
    sql.append("-- THERMOTECH-OPS Database Initialization")
    sql.append("-- Generated by Gemini 3 Pro")
    sql.append("\n-- ===========================================")
    sql.append("-- 1. CLEANUP (Reset Everything)")
    sql.append("-- ===========================================")
    sql.append("DROP TRIGGER IF EXISTS trigger_add_points ON public.daily_assignments;")
    sql.append("DROP FUNCTION IF EXISTS add_points_on_complete();")
    sql.append("DROP TABLE IF EXISTS public.daily_assignments;")
    sql.append("DROP TABLE IF EXISTS public.task_definitions;")
    sql.append("DROP TABLE IF EXISTS public.profiles;")
    
    sql.append("\n-- ===========================================")
    sql.append("-- 2. TABLES SCHEMA")
    sql.append("-- ===========================================")
    
    # PROFILES
    sql.append("""
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Supabase Auth ID usually, but using random for seed
    employee_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    department TEXT,
    job_title TEXT,
    role TEXT DEFAULT 'user', -- 'admin', 'supervisor', 'user'
    points_balance INT DEFAULT 0,
    site_code TEXT DEFAULT 'ALL',
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);""")

    # TASK DEFINITIONS
    sql.append("""
CREATE TABLE public.task_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    frequency TEXT NOT NULL, -- 'daily', 'weekly', 'monthly', 'event_triggered'
    difficulty_level INT DEFAULT 1,
    base_points INT NOT NULL,
    requires_photo BOOLEAN DEFAULT FALSE,
    requires_approval BOOLEAN DEFAULT FALSE,
    default_assignee_id UUID REFERENCES public.profiles(id),
    backup_assignee_id UUID REFERENCES public.profiles(id),
    site_location TEXT, -- '316', '310', 'KS', 'ALL'
    is_active BOOLEAN DEFAULT TRUE,
    source_file TEXT -- For debugging
);""")

    # DAILY ASSIGNMENTS
    sql.append("""
CREATE TABLE public.daily_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_def_id BIGINT REFERENCES public.task_definitions(id),
    user_id UUID REFERENCES public.profiles(id),
    status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'verified', 'abnormal'
    assigned_date DATE DEFAULT CURRENT_DATE,
    completed_at TIMESTAMPTZ,
    photo_url TEXT,
    comment TEXT,
    earned_points INT DEFAULT 0,
    is_incident_report BOOLEAN DEFAULT FALSE
);""")

    sql.append("\n-- ===========================================")
    sql.append("-- 3. SEED DATA: PROFILES")
    sql.append("-- ===========================================")

    # 建立員工對應表 (Name -> UUID)
    emp_name_to_uuid = {}
    
    # 插入員工
    for name, info in employees.items():
        emp_uuid = str(uuid.uuid4())
        emp_name_to_uuid[name] = emp_uuid
        
        # 處理 ID (如果是 TBD，生成一個臨時的)
        emp_id = info["id"]
        if emp_id == "TBD":
            # 簡單雜湊生成一個假 ID
            emp_id = f"TEMP_{abs(hash(name)) % 10000:04d}"
        
        role = "admin" if info["dept"] == "管理部" else "user"
        if "組長" in info["title"] or "主管" in info["title"] or "廠長" in info["title"]:
            role = "supervisor"

        sql.append(f"""
INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('{emp_uuid}', '{emp_id}', '{name}', '{info['dept']}', '{info['title']}', '{role}');""")

    sql.append("\n-- ===========================================")
    sql.append("-- 4. SEED DATA: TASK DEFINITIONS")
    sql.append("-- ===========================================")

    # 插入任務
    for file_data in task_matrices:
        meta = file_data["meta"]
        for task in file_data["tasks"]:
            # 頻率對應分數
            points = 10
            if task["frequency"] == "weekly": points = 50
            if task["frequency"] == "monthly": points = 100
            if task["frequency"] == "event_triggered": points = 20

            # 找 ID
            assignee_id = emp_name_to_uuid.get(task["default_assignee"], "NULL")
            if assignee_id != "NULL": assignee_id = f"'{assignee_id}'"
            
            # 找 backup ID (只取第一個)
            backup_id = "NULL"
            if task["backup_assignees"]:
                backup_name = task["backup_assignees"][0]
                if backup_name in emp_name_to_uuid:
                    backup_id = f"'{emp_name_to_uuid[backup_name]}'"

            sql.append(f"""
INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('{task['title']}', '{task['frequency']}', {points}, '{task['site']}', {assignee_id}, {backup_id}, '{meta['file']}');""")

    sql.append("\n-- ===========================================")
    sql.append("-- 5. TRIGGERS & FUNCTIONS")
    sql.append("-- ===========================================")
    sql.append("""
CREATE OR REPLACE FUNCTION add_points_on_complete()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
    UPDATE public.profiles
    SET points_balance = points_balance + NEW.earned_points
    WHERE id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_add_points
AFTER UPDATE ON public.daily_assignments
FOR EACH ROW
EXECUTE FUNCTION add_points_on_complete();""")

    # 寫入檔案
    output_path = Path("./docs/init_schema_and_seeds.sql")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql))
    
    print(f"✅ SQL 生成完成: {output_path}")

if __name__ == "__main__":
    generate_sql()


