-- THERMOTECH-OPS Database Initialization
-- Generated by Gemini 3 Pro

-- ===========================================
-- 1. CLEANUP (Reset Everything)
-- ===========================================
DROP TRIGGER IF EXISTS trigger_add_points ON public.daily_assignments;
DROP FUNCTION IF EXISTS add_points_on_complete();
DROP TABLE IF EXISTS public.daily_assignments;
DROP TABLE IF EXISTS public.task_definitions;
DROP TABLE IF EXISTS public.profiles;

-- ===========================================
-- 2. TABLES SCHEMA
-- ===========================================

CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Supabase Auth ID usually, but using random for seed
    employee_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    department TEXT,
    job_title TEXT,
    role TEXT DEFAULT 'user', -- 'admin', 'supervisor', 'user'
    points_balance INT DEFAULT 0,
    site_code TEXT DEFAULT 'ALL',
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.task_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    frequency TEXT NOT NULL, -- 'daily', 'weekly', 'monthly', 'event_triggered'
    difficulty_level INT DEFAULT 1,
    base_points INT NOT NULL,
    requires_photo BOOLEAN DEFAULT FALSE,
    requires_approval BOOLEAN DEFAULT FALSE,
    default_assignee_id UUID REFERENCES public.profiles(id),
    backup_assignee_id UUID REFERENCES public.profiles(id),
    site_location TEXT, -- '316', '310', 'KS', 'ALL'
    is_active BOOLEAN DEFAULT TRUE,
    source_file TEXT -- For debugging
);

CREATE TABLE public.daily_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_def_id BIGINT REFERENCES public.task_definitions(id),
    user_id UUID REFERENCES public.profiles(id),
    status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'verified', 'abnormal'
    assigned_date DATE DEFAULT CURRENT_DATE,
    completed_at TIMESTAMPTZ,
    photo_url TEXT,
    comment TEXT,
    earned_points INT DEFAULT 0,
    is_incident_report BOOLEAN DEFAULT FALSE
);

-- ===========================================
-- 3. SEED DATA: PROFILES
-- ===========================================

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('78a6c0da-7b75-4b06-9db7-d13afb0da677', '50095', '阮慧喬', '廠務部', '', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('7ad1a875-2b1e-43b9-9440-4708201d5f32', 'TEMP_6088', '賴葦蓁', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('9b47b7c5-df6b-4ff4-a483-70e886ccca9d', 'TEMP_0229', '阮氏泰娟', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('5c0da29b-7b40-40c0-a2ff-1ceb9e978838', 'TEMP_6208', '林怡彣', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('adcfb6cc-f962-4536-b479-949291142a08', 'TEMP_2572', '張麗卿', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('164ad4dc-2ba5-46aa-899b-70dbbaaa9174', 'TEMP_4613', '武氏燕', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('03f7ab2c-8332-4352-993a-2b2366e67d97', 'TEMP_5413', '范進士', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('ab0c8481-e800-455e-bcb3-c42292dd2ba9', '70037', '温玲怡', '管理部', '會計', 'admin');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('26f2750b-b4fe-4ad8-a966-137861ab5314', 'TEMP_9574', '劉育惠', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('1f9f8858-c767-4e4b-8888-5be16e1d52ce', 'TEMP_2745', '潘芷菱', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('15d1e73f-4adf-4edf-aa94-b6f60f96ab68', 'TEMP_3381', '張夢茹', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('d117681b-24c7-4802-811e-3e28be230175', '70018', '曾世聞', '管理部', '業務', 'admin');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('66c5b0d5-c422-410f-988e-aa1ee5fcc144', 'TEMP_1829', '潘育昌', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '10003', '張庭憲', '廠務部', '廠長', 'supervisor');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('d9bd274f-f90c-4abf-9266-a9fa24204dbd', 'TEMP_9382', '白思恩', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('fc6aa422-4035-4082-8385-807ee1aa7ae8', '50144', '范姜群皓', '廠務部', '組長', 'supervisor');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '30023', '林珠華', '廠務部', '組長', 'supervisor');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('4d14048b-7c2d-410a-b420-51621b00ebdc', 'TEMP_2144', '阮氏河', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('13c323f3-7efe-4c10-a454-731d09ba7698', '30008', '吳春珠', '廠務部', '組長', 'supervisor');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('6beb62ef-1083-4834-a0a4-6bf054a6135a', 'TEMP_8395', '羅玉珍', 'TBD', 'TBD', 'user');

INSERT INTO public.profiles (id, employee_id, full_name, department, job_title, role)
VALUES ('be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', 'TEMP_5729', '黎維俊', 'TBD', 'TBD', 'user');

-- ===========================================
-- 4. SEED DATA: TASK DEFINITIONS
-- ===========================================

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('理布', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '7ad1a875-2b1e-43b9-9440-4708201d5f32', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('產品縫製/開發', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '7ad1a875-2b1e-43b9-9440-4708201d5f32', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('人員訓練/管理', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '164ad4dc-2ba5-46aa-899b-70dbbaaa9174', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('生產線產品檢查', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '7ad1a875-2b1e-43b9-9440-4708201d5f32', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('填寫內外皮QC檢驗表', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', NULL, '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('日用品採購', 'monthly', 100, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '5c0da29b-7b40-40c0-a2ff-1ceb9e978838', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('手縫針管理', 'daily', 10, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '164ad4dc-2ba5-46aa-899b-70dbbaaa9174', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('環境清潔督導', 'weekly', 50, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', 'adcfb6cc-f962-4536-b479-949291142a08', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('3D模子管理', 'weekly', 50, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '9b47b7c5-df6b-4ff4-a483-70e886ccca9d', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('設備保養', 'weekly', 50, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '03f7ab2c-8332-4352-993a-2b2366e67d97', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('生產進度回報', 'weekly', 50, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', '5c0da29b-7b40-40c0-a2ff-1ceb9e978838', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('產品模子拍照給日本確認', 'weekly', 50, 'ALL', '78a6c0da-7b75-4b06-9db7-d13afb0da677', 'adcfb6cc-f962-4536-b479-949291142a08', '工作內容盤點-310電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('國內應收帳款核對/沖銷', 'daily', 10, 'KS,316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', '26f2750b-b4fe-4ad8-a966-137861ab5314', '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('國內應付帳款核對/匯款', 'daily', 10, 'KS,316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', '26f2750b-b4fe-4ad8-a966-137861ab5314', '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('辦公室設備修繕/更換', 'event_triggered', 20, 'KS', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('掃辦公室廁所', 'weekly', 50, 'KS', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('職工福利委員會會議召集/帳務彙整', 'event_triggered', 20, 'KS,316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', NULL, '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('職工福利委員會年度預算/決算/稅務申報', 'event_triggered', 20, 'KS,316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', NULL, '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('跑銀行', 'weekly', 50, 'KS', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', '26f2750b-b4fe-4ad8-a966-137861ab5314', '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('繳納電費/電話費', 'monthly', 100, '316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', NULL, '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('公務車etag儲值', 'event_triggered', 20, 'KS,316,310', 'ab0c8481-e800-455e-bcb3-c42292dd2ba9', NULL, '工作內容盤點-業務部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('與客戶洽談業務', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', NULL, '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('報價單填寫', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('與廠商詢價', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('加工單開立', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', NULL, '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('外出洽談業務', 'weekly', 50, '316', 'd117681b-24c7-4802-811e-3e28be230175', NULL, '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('外出施工', 'weekly', 50, '316', 'd117681b-24c7-4802-811e-3e28be230175', 'd9bd274f-f90c-4abf-9266-a9fa24204dbd', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('送貨', 'weekly', 50, '316', 'd117681b-24c7-4802-811e-3e28be230175', 'd9bd274f-f90c-4abf-9266-a9fa24204dbd', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('出貨處理', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('採購配件', 'weekly', 50, '316', 'd117681b-24c7-4802-811e-3e28be230175', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('現場協調及解釋工單內容', 'daily', 10, '316', 'd117681b-24c7-4802-811e-3e28be230175', NULL, '工作內容盤點-管理部.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('出勤核對加班/請假簽核', 'daily', 10, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('支援主管交辦事項,加工單產線進度,控管生產排程', 'daily', 10, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('外出施工人員安全衛生管理', 'daily', 10, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('品質異常處理與改善', 'monthly', 100, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('巡查機具設備使用狀況', 'daily', 10, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工廠日常用品、五金零件採購', 'daily', 10, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('新進員工生產教育訓練', 'event_triggered', 20, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工廠機台輔助工具製作', 'daily', 10, 'KS,316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('監視系統保養維護', 'monthly', 100, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('廠房配備箱巡查保養', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('頂樓太陽能板清洗保養', 'event_triggered', 20, 'KS', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('發電機(ATS)保養', 'monthly', 100, 'KS,316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('智能機台保養', 'weekly', 50, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('空壓機保養', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('飲水機保養', 'monthly', 100, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('事業生活廢棄物清運', 'weekly', 50, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('棉毯下腳料整理分類清運', 'event_triggered', 20, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('布類下腳料及板材清運', 'event_triggered', 20, '316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('化糞池抽肥', 'event_triggered', 20, 'KS', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('公務車定期檢驗保養', 'event_triggered', 20, 'KS,316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('2.8T天車保養', 'monthly', 100, 'KS,316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('冷氣冷卻水塔清洗', 'monthly', 100, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('貨梯保養(電梯)', 'monthly', 100, 'KS', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('空調冷氣保養', 'event_triggered', 20, 'KS', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('廠房鐵捲門/大門保養', 'monthly', 100, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('消防設備保養/檢查/申報', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('移工勞動部訪查', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工廠加工設備/修繕更換', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '66c5b0d5-c422-410f-988e-aa1ee5fcc144', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('高上廠納管/改善計畫', 'event_triggered', 20, '316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('高上廠員工停車場管理', 'event_triggered', 20, '316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', NULL, '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('高上廠房承租窗口', 'monthly', 100, '316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('ISO審核/廠務部', 'event_triggered', 20, 'KS,316', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('防颱措施事項', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('廠房內外環境驅蟲/消毒', 'monthly', 100, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工廠水電維修', 'event_triggered', 20, 'KS,316,310', '4dcf10ea-ab2b-46f0-b154-2cd1dd338c6f', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '工作內容盤點-高上316接頭組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('環境打掃', 'weekly', 50, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('發工單製作內容', 'daily', 10, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('檢查每工單布料', 'daily', 10, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('領線/布/棉等', 'weekly', 50, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('做完工單檢查QC', 'weekly', 50, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('教新人車縫', 'daily', 10, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('針車保養,冷氣保養', 'weekly', 50, '316', 'c5c42b83-64d9-42fd-b9c6-9f53e4ead3d4', '4d14048b-7c2d-410a-b420-51621b00ebdc', '工作內容盤點-高上316車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工單內容製作', 'daily', 10, 'KS', '13c323f3-7efe-4c10-a454-731d09ba7698', '6beb62ef-1083-4834-a0a4-6bf054a6135a', '工作內容盤點-高獅車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('打掃環境', 'weekly', 50, 'KS', '13c323f3-7efe-4c10-a454-731d09ba7698', '6beb62ef-1083-4834-a0a4-6bf054a6135a', '工作內容盤點-高獅車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('機台保養', 'weekly', 50, 'KS', '13c323f3-7efe-4c10-a454-731d09ba7698', '6beb62ef-1083-4834-a0a4-6bf054a6135a', '工作內容盤點-高獅車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('教育訓練', 'event_triggered', 20, 'KS', '13c323f3-7efe-4c10-a454-731d09ba7698', '6beb62ef-1083-4834-a0a4-6bf054a6135a', '工作內容盤點-高獅車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('參與福委會議', 'event_triggered', 20, 'KS', '13c323f3-7efe-4c10-a454-731d09ba7698', '6beb62ef-1083-4834-a0a4-6bf054a6135a', '工作內容盤點-高獅車縫布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('現場工作進度追蹤', 'daily', 10, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('現場工作安排協調', 'daily', 10, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('工單內容製作', 'daily', 10, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('各組支援', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('外出施工', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', NULL, '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('修理針車', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('更換飲水機濾芯', 'monthly', 100, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('冷氣清洗', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('整理回收', 'monthly', 100, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('現場工作環境整理', 'monthly', 100, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('現場設備修繕/更換', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('防颱準備', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('新進同仁教育訓練', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('ISO內部稽核人員', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('設備盤點', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('下午茶安排', 'monthly', 100, 'KS,316,310', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('活動安排策劃', 'event_triggered', 20, 'KS,316,310', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('掃廁所', 'weekly', 50, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', 'be90ed2a-f160-41e0-aed9-f5ff4cbbc2ba', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('調節組員自身相關問題', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', '15d1e73f-4adf-4edf-aa94-b6f60f96ab68', '工作內容盤點-高獅電熱布包組.xlsx');

INSERT INTO public.task_definitions (title, frequency, base_points, site_location, default_assignee_id, backup_assignee_id, source_file)
VALUES ('參與福委會', 'event_triggered', 20, 'KS', 'fc6aa422-4035-4082-8385-807ee1aa7ae8', NULL, '工作內容盤點-高獅電熱布包組.xlsx');

-- ===========================================
-- 5. TRIGGERS & FUNCTIONS
-- ===========================================

CREATE OR REPLACE FUNCTION add_points_on_complete()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
    UPDATE public.profiles
    SET points_balance = points_balance + NEW.earned_points
    WHERE id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_add_points
AFTER UPDATE ON public.daily_assignments
FOR EACH ROW
EXECUTE FUNCTION add_points_on_complete();