-- =====================================================
-- THERMOTECH-OPS - 簡化版（最安全）
-- =====================================================
-- 只建立表格，不刪除任何東西

-- 建立 profiles 表格（人員）
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    employee_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    department TEXT,
    job_title TEXT,
    role TEXT DEFAULT 'user',
    points_balance INT DEFAULT 0,
    site_code TEXT DEFAULT 'ALL',
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 建立 task_definitions 表格（任務定義）
CREATE TABLE IF NOT EXISTS public.task_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    frequency TEXT NOT NULL,
    difficulty_level INT DEFAULT 1,
    base_points INT NOT NULL,
    requires_photo BOOLEAN DEFAULT FALSE,
    requires_approval BOOLEAN DEFAULT FALSE,
    default_assignee_id UUID REFERENCES public.profiles(id),
    backup_assignee_id UUID REFERENCES public.profiles(id),
    site_location TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    source_file TEXT
);

-- 建立 daily_assignments 表格（每日任務）
CREATE TABLE IF NOT EXISTS public.daily_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_def_id BIGINT REFERENCES public.task_definitions(id),
    user_id UUID REFERENCES public.profiles(id),
    status TEXT DEFAULT 'pending',
    assigned_date DATE DEFAULT CURRENT_DATE,
    completed_at TIMESTAMPTZ,
    photo_url TEXT,
    comment TEXT,
    earned_points INT DEFAULT 0,
    is_incident_report BOOLEAN DEFAULT FALSE
);

-- 建立觸發器函數（自動加分）
CREATE OR REPLACE FUNCTION add_points_on_complete()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'completed' AND (OLD.status IS NULL OR OLD.status != 'completed') THEN
    UPDATE public.profiles
    SET points_balance = points_balance + NEW.earned_points
    WHERE id = NEW.user_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 刪除舊的觸發器（如果存在）
DROP TRIGGER IF EXISTS trigger_add_points ON public.daily_assignments;

-- 建立觸發器
CREATE TRIGGER trigger_add_points
AFTER UPDATE ON public.daily_assignments
FOR EACH ROW
EXECUTE FUNCTION add_points_on_complete();

-- 驗證：檢查表格是否建立成功
SELECT 'Tables created successfully!' as status;

SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name IN ('profiles', 'task_definitions', 'daily_assignments')
ORDER BY table_name;


